# Generated by Django 5.0.3 on 2024-09-20 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practise_app1', '0002_customerfeedback_questions_options_customerresponse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerresponse',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='customerresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='customerresponse',
            name='selected_options',
        ),
        migrations.RemoveField(
            model_name='options',
            name='question',
        ),
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_name', models.CharField(max_length=1000)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerFeedback',
        ),
        migrations.DeleteModel(
            name='CustomerResponse',
        ),
        migrations.DeleteModel(
            name='Options',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
